const SITE_ROOT = "sites";

const worlds = [
  {
    id: "delicate",
    title: "Delicate",
    universe: "Delicate Universe",
    group: "delicate",
    status: "Completed",
    timeframe: "Jan 2019 – Oct 2023",
    endSort: 202310,
    chapters: 180,
    words: 471215,
    lead: "Solar Lee",
    loveInterests: ["Jinhwan", "Jungkook", "Sunwoo"],
    cast: ["Solar Lee", "Kim Jinhwan", "Jeon Jungkook", "Kim Sunwoo"],
    format: "Idolverse · Longform Novel · Scandal Drama · Love Triangle",
    mood: "Interior, aching, glamorous, traumatic, obsessive",
    tagline: "A celebrity world built from interior damage.",
    quote: "You can only run so far from a past this dark.",
    accent: "#ff4f8b",
    worldBg: "radial-gradient(ellipse at 30% 0%, rgba(255,79,139,0.18) 0%, transparent 60%), linear-gradient(180deg, #140812 0%, #100a10 100%)",
    image: "assets/worlds/delicate-solar.jpg",
    heroImage: "assets/worlds/delicate-solar.jpg",
    worldImage: "assets/worlds/delicate-vogue.jpg",
    summary: "Solar Lee, professionally known as Kim Soomi, is YG Entertainment's biggest artist that's taken the world by storm, seemingly overnight since her debut. No one knows where she came from until they do. Behind the green eyes and sold-out stages is a history she left in New York, a dead name, and a past built on the wrong people, choices, and a version of herself she swore she'd gotten away from for good. The Upper East Side is a distant memory long gone, but the past is destined to repeat itself. Perhaps Solar Lee was always meant to be surrounded by chaos, and perhaps a part of her creates it unknowingly. What starts off simple never stays that way, and Solar lives to learn that she must face herself before forgetting.",
    note: "Delicate is both one novel and a series center. Recherche is the prequel, Peace is the aftermath, and Secret shares the wider continuity.",
    songs: [
      { title: "Delicate", artist: "Taylor Swift", src: "assets/audio/TaylorSwift-Delicate.mp3" },
      { title: "My Tears Ricochet", artist: "Taylor Swift", src: "assets/audio/TaylorSwift-mytearsricochet.mp3" },
      { title: "Alive", artist: "B.I", src: "assets/audio/BI-alive.mp3" },
    ],
    site: {
      title: "Delicate World",
      href: `https://kristenmikeska.github.io/delicate-world/`,
      status: "Live",
      preview: "assets/worlds/delicate-portrait.jpg",
      description: "Full character, social, timeline, vault, press, and world archive."
    },
    readers: [
      ["Delicate", "readers/delicate.html"]
    ]
  },
  {
    id: "recherche",
    title: "Recherche",
    universe: "Delicate Universe",
    group: "delicate",
    status: "Unfinished",
    timeframe: "Jan 2020 – Apr 2026",
    endSort: 202604,
    chapters: 38,
    words: 117786,
    lead: "Solar Lee",
    loveInterests: ["Sunwoo"],
    cast: ["Solar Lee", "Kim Sunwoo", "Chaerin Lee", "Jaehyun Lee", "Choi Chanhee"],
    format: "Prequel Novel · Upper East Side · Crime Romance · Coming-of-Age",
    mood: "Castle walls and the price of what lies beyond them · a boy trained to be dangerous before he could choose otherwise · the specific grief of loving someone whose life was decided for them · New York before Korea · the cost of freedom",
    tagline: "Before the fame, there was the fall, and everything that came with it.",
    accent: "#f2b84b",
    worldBg: "radial-gradient(ellipse at 70% 0%, rgba(242,184,75,0.14) 0%, transparent 60%), linear-gradient(180deg, #120e06 0%, #0f0c06 100%)",
    image: "assets/worlds/recherche-city.jpg",
    worldImage: "assets/worlds/recherche-night.jpg",
    summary: "It takes more than fame and money to reside in a prestigious place like the Castle. Only a few families are permitted to live there, and they are known as the richest in all of America. The Lees are one of these families, thanks to Jaesang Lee, the CEO and founder of Lee Industries, the most successful business in the state of New York. From the outside, Solar Lee lives a life of privilege and entitlement. In reality, she is haunted by pressure and the weight of being the expected heir to the company, the realization that her life has already been planned for her, and she gets no say in any of it. She is determined to escape the cage, deciding the consequences are worth it — that is, until she truly learns what it costs to free yourself from the chains of the Upper East Side.",
    note: "Part of the Delicate series continuity, not a standalone reuse.",
    songs: [
      { title: "Falling", artist: "Chase Atlantic", src: "assets/audio/chaseatlantic-falling.mp3" },
      { title: "No Rainbows", artist: "Chase Atlantic", src: "assets/audio/chaseatlantic-norainbows.mp3" },
    ],
    readers: [["Recherche", "readers/recherche.html"]]
  },
  {
    id: "peace",
    title: "Peace",
    universe: "Delicate Universe",
    group: "delicate",
    status: "Unfinished",
    timeframe: "Oct 2023 – Jul 2024",
    endSort: 202407,
    chapters: 10,
    words: 21044,
    lead: "Solar Lee",
    loveInterests: ["Jinhwan", "Jungkook", "Sunwoo"],
    cast: ["Solar Lee", "Kim Jinhwan", "Jeon Jungkook", "Kim Sunwoo", "Chaerin Lee", "Jaehyun Lee"],
    format: "Sequel Novel · Aftermath · Guilt & Accountability · Fractured Reunions",
    mood: "Aftermath, repair, consequence",
    tagline: "Where do you run if the villain was yourself all along?",
    accent: "#9d73ff",
    worldBg: "radial-gradient(ellipse at 50% 0%, rgba(157,115,255,0.15) 0%, transparent 55%), linear-gradient(180deg, #0e0a18 0%, #0c0815 100%)",
    image: "assets/worlds/peace-new.jpg",
    worldImage: "assets/worlds/peace-bridge.jpg",
    summary: "After the events of the warehouse and the sudden disappearance of Korea's most beloved solo artist, Jungkook, Jinhwan, and Sunwoo learn to handle the aftermath of a plan gone haywire, in entirely different ways. Some are gone, but not forgotten, and Solar Lee has reportedly lost her mind and was witness to one of the bloodiest fights in the history of Seoul. The act of avoidance cannot be done when the realization hits that perhaps the villain in the end may be yourself.",
    note: "Belongs after Delicate and should be read as aftermath, not a separate universe.",
    songs: [
      { title: "Peace", artist: "Taylor Swift", src: "assets/audio/TaylorSwift-Peace.mp3" },
      { title: "Epiphany", artist: "Taylor Swift", src: "assets/audio/TaylorSwift-Epiphany.mp3" },
      { title: "Waiting Room", artist: "Phoebe Bridgers", src: "assets/audio/phoebebridgers-waitingroom.mp3" },
    ],
    readers: [["Peace", "readers/peace.html"]]
  },
  {
    id: "secret",
    title: "Secret",
    universe: "Delicate Universe",
    group: "delicate",
    status: "Unfinished",
    timeframe: "Aug 2024 – Jan 2026",
    endSort: 202601,
    chapters: 21,
    words: 40995,
    lead: "Lee Soorin",
    loveInterests: ["Minji", "Yunjin"],
    cast: ["Lee Soorin", "Huh Yunjin", "Kim Minji", "Yang Jungwon"],
    format: "WLW Romance · Idol Industry · Forbidden Love · Identity & Acceptance",
    mood: "Grumpy it girl, labelmate awkwardness, dating-scandal fear, funny until it hurts",
    tagline: "Beloved on main. Exhausted on private.",
    accent: "#31d0c3",
    worldBg: "radial-gradient(ellipse at 60% 0%, rgba(49,208,195,0.15) 0%, transparent 55%), linear-gradient(180deg, #071514 0%, #060f0e 100%)",
    image: "assets/worlds/secret-nearkiss.jpg",
    worldImage: "assets/worlds/secret-hug.jpg",
    summary: "Lee Soorin is the sixth member of the hit girl group LE SSERAFIM, her life was once simple until the day she opened her mouth on live television and uttered the entirely wrong words. She had never looked at a girl before, not in that way, until she laid eyes on Kim Minji. Suddenly, she feels something wrong in her chest, something that she didn't think she'd ever feel, and her knowing best friend seems to have a varying opinion about that despite her supportive smile. What do you do when the world you live in wouldn't accept who you love?",
    note: "Secret shares Delicate's universe through Soomi and the 2018 scandal references, but the lead is Soorin, not Solar.",
    songs: [
      { title: "Secret", artist: "Peach PRC", src: "assets/audio/PeachPRC-Secret.mp3" },
      { title: "Girls Like Girls", artist: "Hayley Kiyoko", src: "assets/audio/hayleykiyoko-girlslikegirls.mp3" },
      { title: "Like A Girl Does", artist: "Peach PRC", src: "assets/audio/peachprc-likeagirldoes.mp3" },
    ],
    readers: [["Secret", "readers/secret.html"]]
  },
  {
    id: "runners",
    title: "Runners",
    universe: "Standalone",
    group: "standalone",
    status: "Unfinished",
    timeframe: "May 2026 – Present",
    endSort: 202606,
    chapters: 50,
    words: 174207,
    lead: "Solar Lee",
    loveInterests: ["Haechan", "Minji"],
    cast: ["Solar Lee", "Jaehyun Lee", "Lee Donghyuck", "Mark Lee", "Kim Minji"],
    format: "Campus Novel · Esports · Greek Life · College Romance · Social Visibility",
    mood: "Pink hoodie gamer girl, campus gossip, soft-launch chaos, rich-family pressure",
    tagline: "Everyone on campus thinks they know Solar Lee.",
    accent: "#31d0c3",
    worldBg: "radial-gradient(ellipse at 20% 0%, rgba(49,208,195,0.2) 0%, transparent 55%), linear-gradient(180deg, #061513 0%, #071410 100%)",
    image: "assets/worlds/runners-new.jpg",
    heroImage: "assets/worlds/runners-alphaphi.png",
    worldImage: "assets/worlds/runners-mirrorselfie.jpg",
    summary: "Solar Lee enrolled at SU to be unremarkable. She had a plan: stay in the gaming lab, avoid the parties, don't become a SUgram story. She is now 0 for 3, possibly 0 for 4 depending on whether you count Haechan. A campus novel about a girl running from visibility in a school that keeps finding her — with an older brother who's already famous, a pink hoodie, and a love situation she's pretending doesn't exist in at least three directions.",
    note: "Standalone continuity, even with Jaehyun and complex-family echoes.",
    songs: [
      { title: "Runners", artist: "Camo", src: "assets/audio/Camo-Runners.mp3" },
      { title: "As Hell", artist: "Chanmina", src: "assets/audio/chanmina-ashell.mp3" },
      { title: "3AM", artist: "ROSÉ", src: "assets/audio/rose-3am.mp3" },
    ],
    site: {
      title: "Runners World",
      href: `https://kristenmikeska.github.io/runners-world/`,
      status: "Live",
      preview: "assets/worlds/runners-alphaphi-new.jpg",
      description: "Campus feed, SUgram, phone threads, people relations, maps, and esports party systems."
    },
    readers: [["Runners", "readers/runners.html"]]
  },
  {
    id: "casual",
    title: "Casual",
    universe: "Standalone",
    group: "standalone",
    status: "Unfinished",
    timeframe: "Jun 2026 – Present",
    endSort: 202606,
    chapters: 20,
    words: 41881,
    lead: "Solar Lee",
    loveInterests: ["Haechan", "Jungwon"],
    cast: ["Solar Lee", "Mark Lee", "Lee Donghyuck", "Yang Jungwon"],
    format: "College Romance · Slow Burn · Found History · Healing Arc",
    mood: "Mercer apartment, old party orbit, Mark history, Haechan seeing too much",
    tagline: "She walked back into a house, a history, and a set of people she never fully left.",
    accent: "#ff8a4c",
    worldBg: "radial-gradient(ellipse at 40% 0%, rgba(255,138,76,0.18) 0%, transparent 55%), linear-gradient(180deg, #130a04 0%, #100805 100%)",
    image: "assets/worlds/casual-new.jpg",
    worldImage: "assets/worlds/casual-solar.jpg",
    summary: "The Mercer apartment is new, but the people surrounding it aren't. She's been here before, yet the terrain doesn't quite feel the same, and neither are the people in it. There's an unexpected difficulty in starting over somewhere you've already been with the same people who knew you before you got cautious, and what happens when someone looks at you like you haven't changed one bit.",
    note: "Casual is a lighter, PG-rated take on the same cast and concept as Runners — both are college AUs with overlapping characters, softer stakes, and a gentler tone. Think of it as a self-contained companion rather than a sequel. Different Solar from Runners and Delicate.",
    songs: [
      { title: "Casual", artist: "Chappell Roan", src: "assets/audio/ChappellRoan-Casual.mp3" },
      { title: "Casual", artist: "Doja Cat", src: "assets/audio/dojacat-casual.mp3" },
    ],
    readers: [["Casual", "readers/casual.html"]]
  },
  {
    id: "hoax",
    title: "Hoax",
    universe: "Standalone",
    group: "standalone",
    status: "Unfinished",
    timeframe: "Jan 2022 – Feb 2026",
    endSort: 202602,
    chapters: 99,
    words: 121721,
    lead: "Solar Kim",
    loveInterests: ["Jungwon", "Jihoon"],
    cast: ["Solar Kim", "Park Jihoon", "Yang Jungwon"],
    format: "Group-chat engine, school/council chaos, ensemble comedy-drama",
    mood: "Loud, unserious until it is not, best-friend wars, chaotic affection",
    tagline: "Loud, unserious, and absolutely catastrophic.",
    accent: "#9d73ff",
    worldBg: "radial-gradient(ellipse at 70% 0%, rgba(157,115,255,0.2) 0%, transparent 55%), linear-gradient(180deg, #0c0918 0%, #0a0815 100%)",
    image: "assets/worlds/hoax-new.jpg",
    worldImage: "assets/worlds/hoax-jungwon.jpg",
    summary: "No one talks about sophomore year, not unless it's for a morbid joke. Solar Lee and her friends are seemingly entirely normal high school students with the sole goal of finishing, until one day, her parents urge her to try out for Student Council President. What's the worst that could happen? That is, until she runs into a certain snobby Student Council President that seems to suddenly always appear at the worst of times, much to the dismay of her best friend that's never quite gotten over his deep crush. Old habits die hard, especially for these friends.",
    note: "This is a major example of recurring names not meaning recurring identity.",
    songs: [
      { title: "Hoax", artist: "Taylor Swift", src: "assets/audio/TaylorSwift-Hoax.mp3" },
      { title: "Someone Like U", artist: "Ariana Grande", src: "assets/audio/arianagrande-someonelikeu.mp3" },
    ],
    readers: [["Hoax", "readers/hoax.html"]]
  },
  {
    id: "havenbrook",
    title: "Havenbrook",
    universe: "Standalone",
    group: "standalone",
    status: "Unfinished",
    timeframe: "May 2026",
    endSort: 202605,
    chapters: 62,
    words: 209489,
    lead: "Solar Lee",
    loveInterests: ["Haechan"],
    cast: ["Solar Lee", "Lee Donghyuck", "Dong Sicheng"],
    format: "Urban backstory, fame aftermath, Overwatch thread",
    mood: "Chain-link, takeout grease, reputation wounds, dangerous tenderness",
    tagline: "The east side of Havenbrook has its own rules.",
    accent: "#91d36e",
    worldBg: "radial-gradient(ellipse at 20% 0%, rgba(145,211,110,0.18) 0%, transparent 55%), linear-gradient(180deg, #0a1208 0%, #080f06 100%)",
    image: "assets/worlds/havenbrook-new.jpg",
    worldImage: "assets/worlds/havenbrook-gang.jpg",
    summary: "The east side of Havenbrook has its own smell and debatable, engraved history, and social rules. DREAM are an underground gang that keeps things orderly and the supply moving. Solar Lee is a high school student with no plans of ever getting involved other than through mutual connections, until Haechan starts to pay too much attention, noticing her before she ever had the chance to process what that costs. But Solar Lee was always meant for places better than Havenbrook.",
    note: "Dark standalone world with DREAM-adjacent danger and a long past/future emotional arc.",
    songs: [
      { title: "You Too", artist: "Chase Atlantic", src: "assets/audio/ChaseAtlantic-youtoo.mp3" },
      { title: "Where Do We Go Now", artist: "Gracie Abrams", src: "assets/audio/GracieAbrams-Wheredowegonow.mp3" },
      { title: "Strawberries and Cigarettes", artist: "Troye Sivan", src: "assets/audio/TroyeSivan-StrawberriesandCigarettes.mp3" },
    ],
    readers: [["Havenbrook", "readers/havenbrook.html"]]
  },
  {
    id: "petal-thorn",
    title: "Petal & Thorn",
    universe: "Standalone",
    group: "standalone",
    status: "Unfinished",
    timeframe: "May 2025 – Feb 2026",
    endSort: 202602,
    chapters: 86,
    words: 194423,
    lead: "Solar Lee",
    loveInterests: ["Jungwon", "Minji"],
    cast: ["Solar Lee", "Yang Jungwon", "Kim Minji", "Huh Yunjin", "Park Jihoon", "Kim Dongjun"],
    format: "Idolverse × Overwatch League × psychological romance",
    mood: "Glossy, spicy, angsty, eccentric, dangerous, hot under stage lights",
    tagline: "Even petals can cut, and thorns can bloom.",
    accent: "#ff4f8b",
    worldBg: "radial-gradient(ellipse at 50% 0%, rgba(255,79,139,0.25) 0%, transparent 55%), linear-gradient(180deg, #130315 0%, #0e031a 100%)",
    image: "assets/worlds/petal-archive-new.jpg",
    heroImage: "assets/worlds/petal-editorial.jpg",
    worldImage: "assets/worlds/petal-thorn-world-new.jpg",
    summary: "Solar Lee has a messy ex in her past that she thought she left behind. As a member of LE SSERAFIM, she is a beloved public figure known for her talent and poise, and now, she's a star DPS player for the San Francisco Shock. Unfortunately, a dark figure from her past has other plans for her, while others have a grudge they won't let go of. With unexpected love interests and new heights, Solar learns to navigate the chaos of the world deciding you didn't have enough on your plate.",
    note: "Core ongoing arcs: the Jihoon entanglement, Shock scouting, Lee sibling dynamics, and Jungwon's Circle backstory.",
    songs: [
      { title: "Crazier", artist: "LE SSERAFIM", src: "assets/audio/LESSERAFIM-crazier.mp3" },
      { title: "Moonstruck", artist: "ENHYPEN", src: "assets/audio/ENHYPEN-moonstruck.mp3" },
      { title: "Dress", artist: "Taylor Swift", src: "assets/audio/TaylorSwift-Dress.mp3" },
    ],
    site: {
      title: "Petal & Thorn World",
      href: `${SITE_ROOT}/petal-thorn-world/index.html`,
      status: "Live",
      preview: "assets/worlds/petal-solarphotoshoot3.jpg",
      description: "Characters, double life, Shock, The Circle, Lee family, timeline, feed, and vault pages."
    },
    readers: [
      ["Petal & Thorn", "readers/petal-thorn.html"]
    ]
  },
  {
    id: "soul-of-minji",
    title: "Soul of Minji",
    universe: "Standalone",
    group: "standalone",
    status: "Completed",
    timeframe: "Aug 2025",
    endSort: 202508,
    chapters: 9,
    words: 15584,
    lead: "Solar",
    loveInterests: ["Minji"],
    cast: ["Minji", "Yunjin", "Cherry"],
    format: "Soul-transfer quest, system objectives, surreal fantasy",
    mood: "Romantic, strange, game-like, heartfelt, unhinged in the best way",
    tagline: "A crash, a missing Minji, and a mission that behaves like a game objective.",
    accent: "#31d0c3",
    worldBg: "radial-gradient(ellipse at 60% 0%, rgba(49,208,195,0.18) 0%, transparent 55%), linear-gradient(180deg, #050e0e 0%, #060c0c 100%)",
    image: "assets/worlds/minji-new.jpg",
    worldImage: "assets/worlds/minji-curtain.jpg",
    summary: "A crash, a missing Minji, two Cherrys, a soul in the wrong body, and a mission route that behaves like a game objective.",
    note: "Short completed work and a strong candidate for a future mini-site.",
    readers: [["Soul of Minji", "readers/soul-of-minji.html"]]
  },
  {
    id: "saint-of-dead-air",
    title: "Saint of Dead Air",
    universe: "Standalone",
    group: "standalone",
    status: "Completed",
    timeframe: "Aug 2025",
    endSort: 202508,
    chapters: 18,
    words: 39057,
    lead: "Jungwon and Solar",
    loveInterests: ["Jungwon", "Minji"],
    cast: ["Jungwon", "Solar", "The Usher", "The Dead Air"],
    format: "Supernatural stage rulebook, liminal rooms, consent magic",
    mood: "Theatre-black, eerie, precise, romantic, rule-bound",
    tagline: "Seven seconds of live silence opens the Dead Air.",
    accent: "#f2b84b",
    worldBg: "radial-gradient(ellipse at 50% 0%, rgba(242,184,75,0.15) 0%, transparent 55%), linear-gradient(180deg, #0d0a04 0%, #0a0802 100%)",
    image: "assets/worlds/soda-couch.jpg",
    worldImage: "assets/worlds/soda-backstage.jpg",
    summary: "Seven seconds of live silence opens the Dead Air, where rooms lie until truth is claimed and consent answers back.",
    note: "This one opens through Jungwon's POV and has one of the clearest rule systems in the archive.",
    readers: [["Saint of Dead Air", "readers/saint-of-dead-air.html"]]
  },
  {
    id: "go",
    title: "GO",
    universe: "Standalone",
    group: "standalone",
    status: "Unfinished",
    timeframe: "Sep 2018 – May 2020",
    endSort: 202005,
    chapters: 39,
    words: 106987,
    lead: "Hyeyeon",
    loveInterests: ["Haechan"],
    cast: ["Jisung", "Si Cheng", "127", "DMHS"],
    format: "High school reputation damage, gang danger, old-friend return",
    mood: "Rain, resentment, lip rings, old betrayal, dangerous boys",
    tagline: "A ruined reputation, and Cheng returning changed in the rain.",
    accent: "#ff8a4c",
    worldBg: "radial-gradient(ellipse at 30% 0%, rgba(255,138,76,0.18) 0%, transparent 55%), linear-gradient(180deg, #100804 0%, #0d0702 100%)",
    image: "assets/worlds/go-haechan.jpg",
    worldImage: "assets/worlds/go-group.jpg",
    summary: "The oldest listed work: Hyeyeon, a ruined reputation, Jisung's daily harassment, and Cheng returning changed in the rain.",
    note: "The MC is Hyeyeon. This one should stay clearly separate from the Solar pattern.",
    songs: [
      { title: "GO", artist: "NCT Dream", src: "assets/audio/NCTDream-GO.mp3" },
    ],
    readers: [["GO", "readers/go.html"]]
  }
];
